from __future__ import annotations

from pathlib import Path

from skyrim_wayfinder.data import load_canonical_content


ROOT = Path(__file__).parents[1]
OUTPUT = ROOT / "docs" / "companions-task-audit.md"
REUSED = {
    "shout_fire_breath_dustmans_cairn",
    "shout_animal_allegiance_ysgramors_tomb",
}


def render_audit() -> str:
    content = load_canonical_content()
    stories = sorted(
        (item for item in content.stories.values() if item.collection_id == "companions"),
        key=lambda item: item.sort_order,
    )
    memberships = [
        item for item in content.memberships.values() if item.story_id in {story.id for story in stories}
    ]
    authored_ids = {
        item.task_id for item in memberships if item.task_id not in REUSED
    }
    lines = [
        "# Companions canonical task audit",
        "",
        "> Generated by `scripts/generate_companions_audit.py`. Canonical JSON remains the source of truth.",
        "",
        "## Scope summary",
        "",
        f"- Stories: **{len(stories)}** (6 REQUIRED, 3 OPTIONAL)",
        f"- New canonical Tasks: **{len(authored_ids)}**",
        f"- Reused Shout Tasks: **{len(REUSED)}**",
        "- Core completion: every applicable REQUIRED membership in the six REQUIRED Stories.",
        "- Optional completion: Totems of Hircine and the two finite Purity Stories; these never block core completion.",
        "",
        "## Stories",
        "",
        "| Story | Classification | Required Tasks | Associated Tasks | Source |",
        "|---|---|---:|---:|---|",
    ]
    for story in stories:
        story_memberships = [item for item in memberships if item.story_id == story.id]
        required = sum(item.completion_role.value == "REQUIRED" for item in story_memberships)
        associated = len(story_memberships) - required
        lines.append(
            f"| {story.display_name} (`{story.id}`) | {story.classification.value} | "
            f"{required} | {associated} | [UESP]({story.source_url}) |"
        )

    lines += [
        "",
        "## Atomic Tasks and progression",
        "",
        "| Story | Task | Role | Behavior | Location → Region | Prerequisites / gates |",
        "|---|---|---|---|---|---|",
    ]
    for story in stories:
        story_memberships = sorted(
            (item for item in memberships if item.story_id == story.id),
            key=lambda item: item.sort_order,
        )
        for membership in story_memberships:
            task = content.tasks[membership.task_id]
            if task.location_id:
                location = content.locations[task.location_id]
                region = content.regions[location.region_id]
                geography = f"{location.display_name} → {region.display_name}"
            else:
                geography = "No fixed location"
            gates = [
                f"`{item.task_id}`" for item in task.prerequisites if item.task_id
            ]
            gates.extend(f"access `{item}`" for item in task.access_condition_ids)
            lines.append(
                f"| {story.display_name} | {task.title} (`{task.id}`) | "
                f"{membership.completion_role.value} | {task.planner_behavior.value} | "
                f"{geography} | {', '.join(gates) or '—'} |"
            )

    lines += [
        "",
        "## Radiant Content Boundary",
        "",
        "Wayfinder models only the four finite radiant progression gates required by the primary questline: one job after Take Up Arms, one after Proving Honor, then two retaliation jobs after The Silver Hand, with the first assigned through Aela. They are locationless MILESTONE Tasks manually confirmed after Skyrim assigns and completes the work. Wayfinder does not predict their quest identity or destination and does not place them in the Regional Planner.",
        "",
        "Intentionally excluded as catalog objectives: Animal Extermination A/B, Hired Muscle, Trouble in Skyrim, Family Heirloom, Escaped Criminal, Rescue Mission, the individual Striking the Heart / Stealing Plans / Retrieval identities, Dragon Seekers, and the incomplete Animal Pelt Collection. Totems of Hircine is retained because it has exactly three finite recoveries; Purity is retained because only Farkas and Vilkas can request it.",
        "",
        "## Lycanthropy and purification",
        "",
        "- `companions_silver_become_werewolf` is permanent historical faction progression.",
        "- `companions_lycanthropy_active` records current Beast Blood state, starts false, is set by the Underforge ritual, is cleared by personal purification, and remains manually correctable.",
        "- Totem Tasks require the current-state condition but never rewrite the historical transformation Task.",
        "- Personal purification is ASSOCIATED and requires a manually maintained spare-head Preparation.",
        "- `access_companions_personal_purification` is initially set after Kodlak is freed. If the immediate opportunity is missed, the user resets that access marker; it becomes derived true after both member Purity Tasks complete.",
        "- No fake leave-the-tomb Task or Witch Head inventory counter is created.",
        "",
        "## AccessCondition bindings",
        "",
        "| Stable condition | Canonical progression binding | Manual correction |",
        "|---|---|---|",
        "| `access_dustmans_cairn` | `companions_proving_accept` | Preserved; manual satisfaction remains additive |",
        "| `access_ysgramors_tomb` | `companions_glory_receive_wuuthrad` | Preserved; manual satisfaction remains additive |",
        "",
        "The stable bridge IDs and existing Shout dependencies remain intact. Real faction progress now satisfies them automatically.",
        "",
        "## Cross-memberships",
        "",
        "- `shout_fire_breath_dustmans_cairn` remains one Shout Task and is ASSOCIATED with Proving Honor.",
        "- `shout_animal_allegiance_ysgramors_tomb` remains one Shout Task and is ASSOCIATED with Glory of the Dead.",
        "- Neither Word Wall is required for Companions completion.",
        "- `companions_glory_receive_wuuthrad` is a stable canonical acquisition/progression Task suitable for a future approved Unique Artifacts membership; none is added here.",
        "",
        "## Geography",
        "",
        "Skyforge (`skyforge`) is a VERIFIED Whiterun EXTERIOR_SITE. All other physical Tasks use previously approved Location → Region assignments. Radiant destinations do not enter canonical geography.",
        "",
        "## Level and branch decisions",
        "",
        "No suggested quest level is encoded as a hard prerequisite. The core questline has no mutually exclusive ending. Optional self-cure can affect current Totem availability but never reverses completed faction history.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    OUTPUT.write_text(render_audit(), encoding="utf-8")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
