from __future__ import annotations

from pathlib import Path

from skyrim_wayfinder.data import load_canonical_content


ROOT = Path(__file__).parents[1]
OUTPUT = ROOT / "docs" / "college-task-audit.md"


def render_audit() -> str:
    content = load_canonical_content()
    stories = sorted(
        (item for item in content.stories.values() if item.collection_id == "college_winterhold"),
        key=lambda item: item.sort_order,
    )
    spell_stories = sorted(
        (item for item in content.stories.values() if item.collection_id == "unique_spells"),
        key=lambda item: item.sort_order,
    )
    college_story_ids = {item.id for item in stories}
    memberships = [item for item in content.memberships.values() if item.story_id in college_story_ids]
    task_ids = {item.task_id for item in memberships}
    lines = [
        "# College of Winterhold canonical task audit",
        "",
        "> Generated by `scripts/generate_college_audit.py`. Canonical JSON remains the source of truth.",
        "",
        "## Scope summary",
        "",
        f"- College Stories: **{len(stories)}** (8 REQUIRED, 10 OPTIONAL)",
        f"- Canonical Tasks appearing in College Stories: **{len(task_ids)}**",
        f"- College-derived Unique Spell identities: **{len(spell_stories)}**",
        "- Core completion requires only applicable REQUIRED memberships in the eight REQUIRED Stories.",
        "- Optional Stories, Shouts, Morokei, Equilibrium, and other cross-domain objectives do not block becoming Arch-Mage.",
        "",
        "## College Stories",
        "",
        "| Story | Classification | Required Tasks | Associated Tasks | Source |",
        "|---|---|---:|---:|---|",
    ]
    for story in stories:
        items = [item for item in memberships if item.story_id == story.id]
        required = sum(item.completion_role.value == "REQUIRED" for item in items)
        lines.append(
            f"| {story.display_name} (`{story.id}`) | {story.classification.value} | {required} | "
            f"{len(items) - required} | [UESP]({story.source_url}) |"
        )

    lines += [
        "",
        "## Atomic Tasks, geography, and prerequisites",
        "",
        "| Story | Task | Role | Behavior | Location → Region | Prerequisites / gates |",
        "|---|---|---|---|---|---|",
    ]
    for story in stories:
        items = sorted(
            (item for item in memberships if item.story_id == story.id),
            key=lambda item: item.sort_order,
        )
        for membership in items:
            task = content.tasks[membership.task_id]
            if task.location_id:
                location = content.locations[task.location_id]
                geography = f"{location.display_name} → {content.regions[location.region_id].display_name}"
            else:
                geography = "No fixed location"
            gates = [f"`{item.task_id}`" for item in task.prerequisites if item.task_id]
            gates.extend(f"access `{item}`" for item in task.access_condition_ids)
            lines.append(
                f"| {story.display_name} | {task.title} (`{task.id}`) | "
                f"{membership.completion_role.value} | {task.planner_behavior.value} | {geography} | "
                f"{', '.join(gates) or '—'} |"
            )

    lines += [
        "",
        "## Access gates and regional aggregation",
        "",
        "- Stable `access_saarthal` is derived from `college_first_lessons`; preserved manual satisfaction remains additive.",
        "- The existing Ice Form Task retains its stable ID and access condition, and is ASSOCIATED with Under Saarthal.",
        "- `college_staff_magnus_accept` is the direct Labyrinthian gate for College progression, Morokei, Slow Time, and Equilibrium.",
        "- `college_revealing_unseen_accept` directly gates Mzulft; no unnecessary Mzulft AccessCondition is introduced.",
        "- Midden work remains assigned to the approved College of Winterhold planning Location.",
        "",
        "## Unique Spells",
        "",
        "| Identity | Shared acquisition Task | College relationship |",
        "|---|---|---|",
    ]
    for story in spell_stories:
        membership = next(item for item in content.memberships.values() if item.story_id == story.id)
        college_links = [
            content.stories[item.story_id].display_name
            for item in content.memberships.values()
            if item.task_id == membership.task_id and item.story_id in college_story_ids
        ]
        lines.append(
            f"| {story.display_name} | `{membership.task_id}` | {', '.join(college_links) or 'Unique Spell only'} |"
        )

    lines += [
        "",
        "Direct ritual rewards, Summon Arniel's Shade, Equilibrium, Vision of the Tenth Eye, and Arniel's Convection use one canonical Task state each. Summon Unbound Dremora is excluded as ritual machinery. Master spells that merely become purchasable remain excluded.",
        "",
        "## Ritual skill milestones",
        "",
        "| School | Official unmodified requirement | Wayfinder behavior |",
        "|---|---:|---|",
        "| Alteration | 90 | Manual MILESTONE; Good Intentions prerequisite |",
        "| Conjuration | 90 | Manual MILESTONE |",
        "| Destruction | 100 | Manual MILESTONE; warning that mods may alter it |",
        "| Illusion | 100 | Manual MILESTONE; warning that mods may alter it |",
        "| Restoration | 90 | Manual MILESTONE; Good Intentions prerequisite |",
        "",
        "Wayfinder does not track live skill values. A completed unlock milestone remains historical if a skill is later made Legendary; temporary in-game interruption can use Blocked/manual correction.",
        "",
        "## Finite vs Repeatable College Content",
        "",
        "Included finite content: Arniel's Endeavor, Brelyna's Practice, J'zargo's Experiment, Onmund's Request, five ritual quests, and the unjournaled Forgotten Names secret. Arniel and Onmund radiant destinations are locationless observed MILESTONE Tasks and never expand canonical geography.",
        "",
        "Excluded repeatable content: Out of Balance, Enchanting Pick-Up, Restocking Soul Gems, Aftershock, Rejoining the College, Tolfdir the Absent-Minded, Fetch Me That Book!, and Shalidor's Insights. Filling Soul Gems, Research Thief, Rogue Wizard, and The Missing Apprentices are excluded unfinished content.",
        "",
        "## Forgotten Names",
        "",
        "Forgotten Names is labeled as an unjournaled, one-time College secret. Its terminal Task records the observed release-or-kill outcome. It is OPTIONAL and never affects core College completion.",
        "",
        "## Stable cross-domain identities",
        "",
        "- `mask_morokei`: REQUIRED for Dragon Priest Masks, ASSOCIATED with The Staff of Magnus.",
        "- `shout_slow_time_labyrinthian`: REQUIRED Shout acquisition, ASSOCIATED with The Staff of Magnus.",
        "- `shout_ice_form_saarthal`: REQUIRED Shout acquisition, ASSOCIATED with Under Saarthal.",
        "- `college_staff_magnus`: REQUIRED College progression; its existing Staff-related secondary membership is preserved without creating a new CollectibleDefinition.",
        "- Septimus, Alftand, Blackreach, and Tower of Mzark remain the existing shared canonical graph; no College duplicates are added.",
        "",
        "## Geography additions",
        "",
        "Windward Ruins → Dawnstar, North Skybound Watch → Falkreath, and Four Skull Lookout → Markarth are VERIFIED EXTERIOR_SITE Locations. Radiant assignments and selectable Dwemer convectors do not enter canonical geography.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    OUTPUT.write_text(render_audit(), encoding="utf-8")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
