"""Generate the approved Thieves Guild task and restoration audit."""
from __future__ import annotations

from pathlib import Path

from skyrim_wayfinder.data.loader import load_canonical_content
from skyrim_wayfinder.domain import CompletionRole, StoryClassification

ROOT = Path(__file__).parents[1]
OUTPUT = ROOT / "docs/thieves-guild-task-audit.md"


def render_audit() -> str:
    content = load_canonical_content()
    stories = sorted(
        (item for item in content.stories.values() if item.collection_id == "thieves_guild"),
        key=lambda item: item.sort_order,
    )
    lines = [
        "# Thieves Guild canonical task audit", "",
        "> Generated by `scripts/generate_thieves_guild_audit.py` from canonical content. Product-approved Increment 2H scope; no other faction population.", "",
        f"- REQUIRED Stories: {sum(s.classification is StoryClassification.REQUIRED for s in stories)}",
        f"- OPTIONAL Stories: {sum(s.classification is StoryClassification.OPTIONAL for s in stories)}",
        f"- Finite city-progress records: {len(content.finite_progress)}",
        "", "## Narrative Completion vs Full Guild Restoration", "",
        "Mercer/Nightingale narrative completion is derived from **Darkness Returns**. Full Guild restoration is derived from **Under New Management**; no synthetic completion Stories exist. The latter requires Darkness Returns plus all four city influence quests, but the four city branches can progress independently of the Mercer story once Guild jobs are available.", "",
        "Full `thieves_guild` collection completion uses all REQUIRED Story Tasks and therefore cannot be reached by finishing Darkness Returns alone. OPTIONAL Stories are outside that denominator. Both observed outcomes of Brynjolf's initial scheme permit progression.", "",
        "Source: [Thieves Guild](https://en.uesp.net/wiki/Skyrim:Thieves_Guild_(faction)); [Under New Management](https://en.uesp.net/wiki/Skyrim:Under_New_Management).", "",
        "## Complete Story list", "", "| Story | Classification | Source |", "|---|---|---|",
    ]
    for story in stories:
        lines.append(f"| {story.display_name} (`{story.id}`) | {story.classification.value} | [UESP]({story.source_url}) |")
    lines += ["", "## Central narrative sequence", "", "The first eleven REQUIRED Stories follow A Chance Arrangement → Taking Care of Business → Loud and Clear → Dampened Spirits → Scoundrel's Folly → Speaking With Silence → Hard Answers → The Pursuit → Trinity Restored → Blindsighted → Darkness Returns. A Chance Arrangement can fail without blocking Taking Care of Business. Meet the Family is concurrent optional onboarding, not a hard narrative gate.", "",
              "## Finite Reputation Progress vs Repeatable Jobs", "", "Only successfully completed qualifying jobs count. Delvin offers Numbers, Fishing, and Bedlam; Vex offers Burglary, Shill, Sweep, and Heist. These seven job types are repeatable mechanisms, not permanent completion identities. Canceled/failed assignments, Riften jobs, and Solstheim jobs do not increment the four city records. Random targets/destinations are not canonical Locations. Decorative trophy milestones and the 125-job safe are excluded.", "", "| Counter | Required | Unlocks |", "|---|---:|---|" ]
    jobs = {"markarth": "Silver Lining", "solitude": "The Dainty Sload", "whiterun": "Imitation Amnesty", "windhelm": "Summerset Shadows"}
    for city in ("whiterun", "markarth", "solitude", "windhelm"):
        definition = content.finite_progress[f"guild_influence_{city}"]
        lines.append(f"| {definition.display_name} (`{definition.id}`) | {definition.required_count} | {jobs[city]} |")
    lines += ["", "Each counter is persisted as a clamped 0–5 integer, separate from Task state. Later downward correction relocks unfinished special jobs but never erases completed historical Tasks. [Source](https://en.uesp.net/wiki/Skyrim:Thieves_Guild_(faction)#Special_Job_Quests).", "",
              "## Four special jobs", "", "| Story / city | Unlock | Fixed route | Restoration effect |", "|---|---|---|---|"]
    specials = [
        ("Silver Lining / Markarth", "guild_influence_markarth = 5", "Ragged Flagon → Markarth / Endon → Pinewatch → Markarth", "Markarth influence; Endon fence"),
        ("The Dainty Sload / Solitude", "guild_influence_solitude = 5", "Ragged Flagon → Solitude / Erikur → The Red Wave → Dainty Sload → Solitude", "Solitude influence"),
        ("Imitation Amnesty / Whiterun", "guild_influence_whiterun = 5", "Ragged Flagon → Whiterun / Olfrid → Dragonsreach → Whiterun", "Whiterun influence"),
        ("Summerset Shadows / Windhelm", "guild_influence_windhelm = 5", "Ragged Flagon → Windhelm / Torsten and Niranye → Uttering Hills Cave → Windhelm", "Windhelm influence; Niranye fence"),
    ]
    for title, unlock, route, effect in specials:
        lines.append(f"| {title} | `{unlock}` | {route} | {effect} |")
    lines += ["", "## Skeleton Key Acquisition vs Return", "", "`artifact_skeleton_key_acquire` is the one canonical historical acquisition event. It retains its Daedric collectible credit and gains a REQUIRED secondary membership in Blindsighted. It requires defeating Mercer, beyond merely entering Irkngthand. `guild_dark_return_key` is a separate required event at the Twilight Sepulcher; returning the Key never clears its acquisition state. [Blindsighted](https://en.uesp.net/wiki/Skyrim:Blindsighted); [Darkness Returns](https://en.uesp.net/wiki/Skyrim:Darkness_Returns).", "",
              "## Access bridges and cross-memberships", "", "`access_snow_veil_sanctum` derives from `guild_snow_open`, while preserving manual override. The unchanged `shout_disarm_snow_veil_sanctum` is ASSOCIATED with Speaking With Silence and remains optional. The Model Ship is also ASSOCIATED there. `access_blindsighted_irkngthand` derives from `guild_blind_enter`; the Left Eye is ASSOCIATED with Blindsighted, and Skeleton Key acquisition is REQUIRED. All three are separate Tasks on the same Irkngthand Location card when actionable.", "",
              "## Nightingale rewards", "", "Stable faction Tasks record Nightingale Armor, the oath, and initial Agent-role selection. The initial role Task stores the observed Shadow/Subterfuge/Strife outcome. These replaceable powers are not added to Unique Spells & Powers now, nor are Nightingale/Guild Master equipment items given collectible identities. [Darkness Returns](https://en.uesp.net/wiki/Skyrim:Darkness_Returns); [Powers](https://en.uesp.net/wiki/Skyrim:Powers).", "",
              "## Finite OPTIONAL content and exclusions", "", "Meet the Family, Toying With The Dead, the Caravan Fence Quest, Vald's Debt, and the Litany of Larceny are OPTIONAL. Vald's Debt becomes obsolete after Mercer's plans are taken by another route, without erasing prior completion. Reparations is repeatable recovery machinery and is excluded; temporary expulsion is not modeled as a permanent faction failure. Paid in Full is deferred to Dragonborn. No Stone Unturned/Stones of Barenziah and its 24 stones are deferred.", "",
              "## The Litany of Larceny", "", "The optional Story tracks seven historical acquisitions; selling to Delvin is not a separate completion requirement. The Model Ship and Left Eye have prominent before-you-leave warnings, but are not silently declared permanently impossible after the first visit. No broader collectible collection is created. [Source](https://en.uesp.net/wiki/Skyrim:The_Litany_of_Larceny).", "", "| Item | Location / Region | Associated Guild Story |", "|---|---|---|"]
    for short, associated in (("bee", "Loud and Clear"), ("decanter", "Dampened Spirits"), ("map", "Scoundrel's Folly"), ("ship", "Speaking With Silence"), ("cube", "Hard Answers"), ("bust", "The Pursuit"), ("eye", "Blindsighted")):
        task = content.tasks[f"guild_litany_{short}"]
        place = content.locations[task.location_id]
        region = content.regions[place.region_id]
        lines.append(f"| {task.title} (`{task.id}`) | {place.display_name} / {region.display_name} | {associated} (ASSOCIATED) |")
    lines += ["", "## Atomic Tasks and geography", "", "| Story | Task | Location / Region | Prerequisites | Role | Source |", "|---|---|---|---|---|---|"]
    for story in stories:
        memberships = sorted((m for m in content.memberships.values() if m.story_id == story.id), key=lambda m: m.sort_order)
        for membership in memberships:
            task = content.tasks[membership.task_id]
            place = content.locations.get(task.location_id or "")
            geography = f"{place.display_name} / {content.regions[place.region_id].display_name}" if place else task.planner_behavior.value
            requirements = ", ".join(
                f"{p.type}:{p.task_id or p.finite_progress_id}" for p in task.prerequisites
            ) or "—"
            lines.append(f"| {story.display_name} | {task.title} (`{task.id}`) | {geography} | {requirements} | {membership.completion_role.value} | [UESP]({task.source_url}) |")
    lines += ["", "## Geography additions", "", "The Red Wave → Solitude (EXTERIOR_SITE); Lake Honrich — Quill Wreck → Riften (EXTERIOR_SITE). Both are verified fixed objectives. Calcelmo's laboratory is represented by Understone Keep; the Brinewater route by East Empire Company Warehouse. Castle Karstaag Caverns is deferred with Paid in Full. The catalog contains 248 Locations; no random radiant target was added.", "",
              "## Unresolved boundaries", "", "Future Product decisions: whether/how three switchable Agent powers belong in Unique Spells & Powers; future unique equipment/valuables collectible cross-membership; Paid in Full when Dragonborn content is authored. Current Guild scope and completion gates have no unresolved blocker.", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    OUTPUT.write_text(render_audit(), encoding="utf-8")
    print(f"Wrote {OUTPUT}")
