from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

from skyrim_wayfinder.data import load_canonical_content
from skyrim_wayfinder.domain import VerificationStatus


ROOT = Path(__file__).resolve().parents[1]
COVERAGE_PATH = ROOT / "docs" / "geography-coverage.json"
OUTPUT_PATH = ROOT / "docs" / "geography-catalog-review.md"


def escaped(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def link_list(urls: tuple[str, ...]) -> str:
    return ", ".join(f"[source {index}]({url})" for index, url in enumerate(urls, start=1))


def render_review() -> str:
    content = load_canonical_content()
    coverage = json.loads(COVERAGE_PATH.read_text(encoding="utf-8"))
    domains_by_location: dict[str, list[str]] = defaultdict(list)
    for domain in coverage["domains"]:
        for location_id in domain["location_ids"]:
            if location_id not in content.locations:
                raise ValueError(f"Coverage references unknown Location: {location_id}")
            domains_by_location[location_id].append(domain["name"])

    uncovered = sorted(set(content.locations) - set(domains_by_location))
    if uncovered:
        raise ValueError(f"Locations lack completion-scope coverage: {uncovered}")

    reviews = coverage["review_assignments"]
    required_reviews = {
        item.id for item in content.locations.values()
        if item.verification_status is VerificationStatus.REVIEW_REQUIRED
    }
    if required_reviews != set(reviews):
        raise ValueError(
            f"Review detail mismatch; missing={sorted(required_reviews - set(reviews))}, "
            f"extra={sorted(set(reviews) - required_reviews)}"
        )

    by_region: dict[str, list] = defaultdict(list)
    for location in content.locations.values():
        by_region[location.region_id].append(location)

    lines = [
        "# Geography catalog review",
        "",
        "> Generated by `scripts/generate_geography_review.py` from canonical Region/Location data and "
        "`docs/geography-coverage.json`. Do not edit counts or review rows by hand.",
        "",
        "## Scope and source strategy",
        "",
        coverage["scope"],
        "",
        "UESP is the primary practical source. Each canonical Location carries its narrowest useful factual "
        "source URL(s). Quest and collection overview pages in the coverage inventory establish why destinations "
        "are required. Dynamically selected and radiant-only destinations do not expand the catalog.",
        "",
        f"**Catalog totals:** {len(content.regions)} Travel Regions; {len(content.locations)} Locations; "
        f"{len(required_reviews)} Locations awaiting Product review.",
        "",
        "## Travel Regions",
        "",
        "| Region | Type | Locations | Principal hub | Planning rationale |",
        "|---|---:|---:|---|---|",
    ]
    for region in sorted(content.regions.values(), key=lambda item: item.sort_order):
        locations = by_region.get(region.id, [])
        lines.append(
            f"| {escaped(region.display_name)} (`{region.id}`) | {region.region_type.value} | "
            f"{len(locations)} | {escaped(region.principal_hub)} | {escaped(region.rationale)} |"
        )

    lines += ["", "## Approved completion-scope decisions", ""]
    for decision in coverage.get("scope_decisions", []):
        sources = link_list(tuple(decision["source_urls"]))
        locations = ", ".join(f"`{item}`" for item in decision["location_ids"]) or "None"
        lines += [
            f"### {decision['reward']}",
            "",
            f"- **Disposition:** {decision['disposition']}",
            f"- **Catalog Locations:** {locations}",
            f"- **Reason:** {decision['reason']}",
            f"- **Evidence:** {sources}",
            "",
        ]

    lines += [
        "## REVIEW_REQUIRED Location assignments",
        "",
        "Every Location owns exactly one Travel Region. This table must remain empty before Task population.",
        "",
        "| Location | Provisional Region | Alternative(s) | Why ambiguous | Evidence |",
        "|---|---|---|---|---|",
    ]
    for location_id in sorted(required_reviews, key=lambda item: content.locations[item].display_name):
        location = content.locations[location_id]
        review = reviews[location_id]
        alternatives = ", ".join(review["alternatives"])
        lines.append(
            f"| {escaped(location.display_name)} (`{location.id}`) | "
            f"{escaped(content.regions[location.region_id].display_name)} (`{location.region_id}`) | "
            f"{escaped(alternatives)} | {escaped(review['reason'])} | {link_list(location.source_urls)} |"
        )

    lines += [
        "",
        "## Completion-scope coverage",
        "",
        "| Planned domain | Required Locations | Research source(s) |",
        "|---|---:|---|",
    ]
    for domain in coverage["domains"]:
        urls = tuple(domain["source_urls"])
        lines.append(f"| {domain['name']} | {len(set(domain['location_ids']))} | {link_list(urls)} |")

    lines += [
        "",
        "## Location coverage inventory",
        "",
        "This generated inversion of the machine-readable inventory shows why every Location entered the catalog.",
        "",
        "| Location | Region | Type | Introduced by | Required by planned domains | Status |",
        "|---|---|---|---|---|---|",
    ]
    for location in sorted(content.locations.values(), key=lambda item: (content.regions[item.region_id].sort_order, item.display_name)):
        required_by = "; ".join(sorted(domains_by_location[location.id]))
        lines.append(
            f"| {escaped(location.display_name)} (`{location.id}`) | "
            f"{escaped(content.regions[location.region_id].display_name)} | {location.location_type.value} | "
            f"{location.content_source.value} | {escaped(required_by)} | {location.verification_status.value} |"
        )

    lines += [
        "",
        "## Geography Foundation closure",
        "",
        "- The two-region Solstheim model is Product-approved.",
        "- All catalog Locations have verified Survival-planning assignments.",
        "- The coverage inventory excludes radiant-only and Creation Club destination expansion.",
        "- Bulk Task population remains a separate, subsequent increment.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    OUTPUT_PATH.write_text(render_review(), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
